name: CI

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Or 'zulu', 'adopt', etc.

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # Replaces gradle/gradle-build-action
      # with:
      #   gradle-version: 'wrapper' # Use the version specified in gradle-wrapper.properties
      #   cache-read-only: ${{ github.ref != 'refs/heads/main' }} # Example: Cache only on main branch pushes

    - name: Build with Gradle
      run: ./gradlew build

    # 'check' task usually runs tests as well. If you have a separate test command, add it.
    # - name: Test with Gradle
    #   run: ./gradlew check # or ./gradlew test

    # Example of caching Gradle dependencies (optional, setup-gradle might handle some caching)
    # - name: Cache Gradle packages
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.gradle/caches
    #       ~/.gradle/wrapper
    #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    #     restore-keys: |
    #       ${{ runner.os }}-gradle-
